#############################################################################
# Generated by PAGE version 4.12
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m38" -background {#d3d3d3} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm withdraw $top
    wm focusmodel $top passive
    wm geometry $top 967x763+473+136
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1030
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm title $top "Memory Simulator"
    vTcl:DefineAlias "$top" "MemorySimulator" vTcl:Toplevel:WidgetProc "" 1
    set site_3_0 $top.m38
    menu $site_3_0 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    vTcl:DefineAlias "$site_3_0" "FileSelect" vTcl:WidgetProc "" 1
    $site_3_0 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#fileSelected} -font TkMenuFont \
        -foreground {#000000} -label File 
    button $top.but41 \
        -activebackground {#000000} -activeforeground {#000000} \
        -background {#000000} -command nextButtonClicked \
        -disabledforeground {#a3a3a3} -foreground {#ffffff} \
        -highlightbackground {#000000} -highlightcolor black -pady 0 \
        -text Next 
    vTcl:DefineAlias "$top.but41" "NextButton" vTcl:WidgetProc "MemorySimulator" 1
    message $top.mes45 \
        -background {#ffffff} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Message \
        -textvariable fileContent -width 246 
    vTcl:DefineAlias "$top.mes45" "Message1" vTcl:WidgetProc "MemorySimulator" 1
    message $top.mes46 \
        -background {#ffff00} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Message \
        -width 136 
    vTcl:DefineAlias "$top.mes46" "Frame1" vTcl:WidgetProc "MemorySimulator" 1
    message $top.mes47 \
        -background {#ffffff} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Message \
        -width 136 
    vTcl:DefineAlias "$top.mes47" "Frame2" vTcl:WidgetProc "MemorySimulator" 1
    message $top.mes48 \
        -background {#ffff00} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Message \
        -width 136 
    vTcl:DefineAlias "$top.mes48" "Frame3" vTcl:WidgetProc "MemorySimulator" 1
    message $top.mes49 \
        -background {#ffffff} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Message \
        -width 136 
    vTcl:DefineAlias "$top.mes49" "Frame4" vTcl:WidgetProc "MemorySimulator" 1
    message $top.mes50 \
        -background {#ffff00} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Message \
        -width 136 
    vTcl:DefineAlias "$top.mes50" "Frame5" vTcl:WidgetProc "MemorySimulator" 1
    message $top.mes51 \
        -background {#ffffff} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Message \
        -width 136 
    vTcl:DefineAlias "$top.mes51" "Frame6" vTcl:WidgetProc "MemorySimulator" 1
    message $top.mes52 \
        -background {#ffff00} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Message \
        -width 136 
    vTcl:DefineAlias "$top.mes52" "Frame7" vTcl:WidgetProc "MemorySimulator" 1
    message $top.mes53 \
        -background {#ffffff} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Message \
        -width 136 
    vTcl:DefineAlias "$top.mes53" "Frame8" vTcl:WidgetProc "MemorySimulator" 1
    message $top.mes54 \
        -background {#ffffff} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Message \
        -width 356 
    vTcl:DefineAlias "$top.mes54" "Message4" vTcl:WidgetProc "MemorySimulator" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but41 \
        -in $top -x 150 -y 470 -anchor nw -bordermode ignore 
    place $top.mes45 \
        -in $top -x 50 -y 20 -width 246 -relwidth 0 -height 430 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes46 \
        -in $top -x 360 -y 20 -width 136 -relwidth 0 -height 70 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes47 \
        -in $top -x 360 -y 90 -width 136 -relwidth 0 -height 70 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes48 \
        -in $top -x 360 -y 160 -width 136 -height 70 -anchor nw \
        -bordermode inside 
    place $top.mes49 \
        -in $top -x 360 -y 230 -width 136 -height 70 -anchor nw \
        -bordermode inside 
    place $top.mes50 \
        -in $top -x 360 -y 300 -width 136 -height 70 -anchor nw \
        -bordermode inside 
    place $top.mes51 \
        -in $top -x 360 -y 370 -width 136 -height 70 -anchor nw \
        -bordermode inside 
    place $top.mes52 \
        -in $top -x 360 -y 440 -width 136 -height 70 -anchor nw \
        -bordermode inside 
    place $top.mes53 \
        -in $top -x 360 -y 510 -width 136 -height 70 -anchor nw \
        -bordermode inside 
    place $top.mes54 \
        -in $top -x 560 -y 20 -width 356 -relwidth 0 -height 690 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

