#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.12
# In conjunction with Tcl version 8.6
#    Mar 27, 2018 06:51:38 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from Tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import GUI_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    GUI_support.set_Tk_var()
    top = Memory_Simulator (root)
    GUI_support.init(root, top)
    root.mainloop()

w = None
def create_Memory_Simulator(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    GUI_support.set_Tk_var()
    top = Memory_Simulator (w)
    GUI_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Memory_Simulator():
    global w
    w.destroy()
    w = None


class Memory_Simulator:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("967x763+473+136")
        top.title("Memory Simulator")
        top.configure(background="#d3d3d3")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)
        #file button
        self.menubar.add_command(
                activebackground="#d8d8d8",
                activeforeground="#000000",
                background="#d9d9d9",
                command=GUI_support.fileSelected,
                font="TkMenuFont",
                foreground="#000000",
                label="File")



        #next button
        self.NextButton = Button(top)
        self.NextButton.place(relx=0.16, rely=0.62, height=33, width=43)
        self.NextButton.configure(activebackground="#000000")
        self.NextButton.configure(activeforeground="white")
        self.NextButton.configure(activeforeground="#000000")
        self.NextButton.configure(background="#000000")
        self.NextButton.configure(command=GUI_support.nextButtonClicked)
        self.NextButton.configure(disabledforeground="#a3a3a3")
        self.NextButton.configure(foreground="#ffffff")
        self.NextButton.configure(highlightbackground="#000000")
        self.NextButton.configure(highlightcolor="black")
        self.NextButton.configure(pady="0")
        self.NextButton.configure(text='''Next''')
        #message window for file output
        self.Message1 = Message(top)
        self.Message1.place(relx=0.05, rely=0.03, relheight=0.56, relwidth=0.25)
        self.Message1.configure(background="#ffffff")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''Message''')
        self.Message1.configure(textvariable=GUI_support.fileContent)
        self.Message1.configure(width=246)
        #message windows for 8 frames
        self.Frame1 = Message(top)
        self.Frame1.place(relx=0.37, rely=0.03, relheight=0.09, relwidth=0.14)
        self.Frame1.configure(background="#ffff00")
        self.Frame1.configure(foreground="#000000")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(text='''Message''')
        self.Frame1.configure(textvariable=GUI_support.messageBoxStrings[0])
        self.Frame1.configure(width=136)

        self.Frame2 = Message(top)
        self.Frame2.place(relx=0.37, rely=0.12, relheight=0.09, relwidth=0.14)
        self.Frame2.configure(background="#ffffff")
        self.Frame2.configure(foreground="#000000")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")
        self.Frame2.configure(text='''Message''')
        self.Frame2.configure(textvariable=GUI_support.messageBoxStrings[1])
        self.Frame2.configure(width=136)

        self.Frame3 = Message(top)
        self.Frame3.place(relx=0.37, rely=0.21, relheight=0.09, relwidth=0.14)
        self.Frame3.configure(background="#ffff00")
        self.Frame3.configure(foreground="#000000")
        self.Frame3.configure(highlightbackground="#d9d9d9")
        self.Frame3.configure(highlightcolor="black")
        self.Frame3.configure(text='''Message''')
        self.Frame3.configure(textvariable=GUI_support.messageBoxStrings[2])
        self.Frame3.configure(width=136)

        self.Frame4 = Message(top)
        self.Frame4.place(relx=0.37, rely=0.3, relheight=0.09, relwidth=0.14)
        self.Frame4.configure(background="#ffffff")
        self.Frame4.configure(foreground="#000000")
        self.Frame4.configure(highlightbackground="#d9d9d9")
        self.Frame4.configure(highlightcolor="black")
        self.Frame4.configure(text='''Message''')
        self.Frame4.configure(textvariable=GUI_support.messageBoxStrings[3])
        self.Frame4.configure(width=136)

        self.Frame5 = Message(top)
        self.Frame5.place(relx=0.37, rely=0.39, relheight=0.09, relwidth=0.14)
        self.Frame5.configure(background="#ffff00")
        self.Frame5.configure(foreground="#000000")
        self.Frame5.configure(highlightbackground="#d9d9d9")
        self.Frame5.configure(highlightcolor="black")
        self.Frame5.configure(text='''Message''')
        self.Frame5.configure(textvariable=GUI_support.messageBoxStrings[4])
        self.Frame5.configure(width=136)

        self.Frame6 = Message(top)
        self.Frame6.place(relx=0.37, rely=0.48, relheight=0.09, relwidth=0.14)
        self.Frame6.configure(background="#ffffff")
        self.Frame6.configure(foreground="#000000")
        self.Frame6.configure(highlightbackground="#d9d9d9")
        self.Frame6.configure(highlightcolor="black")
        self.Frame6.configure(text='''Message''')
        self.Frame6.configure(textvariable=GUI_support.messageBoxStrings[5])
        self.Frame6.configure(width=136)

        self.Frame7 = Message(top)
        self.Frame7.place(relx=0.37, rely=0.58, relheight=0.09, relwidth=0.14)
        self.Frame7.configure(background="#ffff00")
        self.Frame7.configure(foreground="#000000")
        self.Frame7.configure(highlightbackground="#d9d9d9")
        self.Frame7.configure(highlightcolor="black")
        self.Frame7.configure(text='''Message''')
        self.Frame7.configure(textvariable=GUI_support.messageBoxStrings[6])
        self.Frame7.configure(width=136)

        self.Frame8 = Message(top)
        self.Frame8.place(relx=0.37, rely=0.67, relheight=0.09, relwidth=0.14)
        self.Frame8.configure(background="#ffffff")
        self.Frame8.configure(foreground="#000000")
        self.Frame8.configure(highlightbackground="#d9d9d9")
        self.Frame8.configure(highlightcolor="black")
        self.Frame8.configure(text='''Message''')
        self.Frame8.configure(textvariable=GUI_support.messageBoxStrings[7])
        self.Frame8.configure(width=136)
        #message box for loading statements
        self.Message4 = Message(top)
        self.Message4.place(relx=0.58, rely=0.03, relheight=0.9, relwidth=0.37)
        self.Message4.configure(background="#ffffff")
        self.Message4.configure(foreground="#000000")
        self.Message4.configure(highlightbackground="#d9d9d9")
        self.Message4.configure(highlightcolor="black")
        self.Message4.configure(text='''Message''')
        self.Message4.configure(textvariable = GUI_support.pagesLoaded)
        self.Message4.configure(width=356)
        #ntry for user to input frame size
        self.RamField = Entry(top)
        self.RamField.place(relx=0.12, rely=0.77,height=24, relwidth=0.1)
        self.RamField.configure(background="white")
        self.RamField.configure(disabledforeground="#a3a3a3")
        self.RamField.configure(font="TkFixedFont")
        self.RamField.configure(foreground="#000000")
        self.RamField.configure(insertbackground="black")
        self.RamField.configure(textvariable=GUI_support.ramSize)
        self.RamField.configure(width=94)




if __name__ == '__main__':
    vp_start_gui()



